### ISSUE TITLE
Few Issues w/ Portfolio

### ISSUE THREAD

**Issue by JosChavz** [KyrelJerome/KyrelJerome.github.io#1]
Howdy,

There happen to be a few issues with your site. I am on FireFox, just letting you know.
First, the y-axis is overflowed, so you could simply fix that by hiding that in the body element. 

Next, more of a feedback, the nav bar should have a background color to it because, at some points in your site, the nav is not well seen. Also, the hover color doesn't really go well with the site's color. As for the header, where it says '
Hi, I'm
Kyrel Jerome
Front-End Developer
', I think there needs to be more spacing top and bottom, equally! Same goes for your footer. 
Good stuff though!

Cheers,
Jose Chavez

**Comment by KyrelJerome** [comment]
Fixed!
